### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by GenevieveBuckley** [portugueslab/napari-hdf5#1]
I get an error when I try to install this package, either by `pip install git+https://github.com/portugueslab/napari-hdf5.git`, or by cloning the repository & `pip install -e .`

I've tried this with python 3.9 and 3.10; on an M1 macbook and also on a linux remote machine.

Here is the full traceback:
```python-traceback
(napari) [genevieb@m3-login1 ~]$ pip install git+https://github.com/portugueslab/napari-hdf5.git
Collecting git+https://github.com/portugueslab/napari-hdf5.git
  Cloning https://github.com/portugueslab/napari-hdf5.git to /tmp/pip-req-build-yzmh686q
  Running command git clone --quiet https://github.com/portugueslab/napari-hdf5.git /tmp/pip-req-build-yzmh686q
  Resolved https://github.com/portugueslab/napari-hdf5.git to commit 1492a13b2e48ff629cfeb165430e613a7df65665
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/genevieb/em95/miniconda/conda/envs/napari/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/genevieb/em95/miniconda/conda/envs/napari/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/genevieb/em95/miniconda/conda/envs/napari/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 139, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 275, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 59, in _assign_version
          maybe_version = _get_version(config)
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 163, in _get_version
          dump_version(
        File "/tmp/pip-build-env-4020s6th/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 78, in dump_version
          with open(target, "w") as fp:
      FileNotFoundError: [Errno 2] No such file or directory: 'pkg/version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This package doesn't seem to be distributed on PyPI, so I wanted to flag for you that there's a problem installing it directly from github or the cloned repository as well.

**Comment by GenevieveBuckley** [comment]
Ah, looking at the code it seems like most of the content is the default cookiecutter template. So it might not matter anyway!
